# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d7ca7d99513fe1ea45643804f1666d8cd1a3fceb11b21bcc2631c92dd3160d7582aa2d0d6664b0719b784d3c7d8852e90187b1c707d537c64a04f0ccfdb17af

test:
  secret_key_base: 6871ac5b91a985b4c69e76a8c1fd6f93b8691574c3a850b4ac73888f4b152d19a89db86abc3c84ab0c8455427225875bf30fa44c032e642321dde0957bf70625

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
